CREATE TABLE IF NOT EXISTS Funcionario (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(200) NOT NULL,
    CPF CHAR(11) NOT NULL,
    Nascimento DATE NOT NULL,
    Cargo VARCHAR(200) NOT NULL,
    Admissao DATE NOT NULL,
    Status BIT NOT NULL
);